updated workflow

diff --git a/.github/workflows/linting_formatting_testing.yml b/.github/workflows/linting_formatting_testing.yml
--- a/.github/workflows/linting_formatting_testing.yml
+++ b/.github/workflows/linting_formatting_testing.yml
@@ -22,8 +22,8 @@ jobs:
         options: >-
           --health-cmd pg_isready -U surfaceinterval -d surface-interval-db
           --health-interval 10s
-          --health-timeout 5s
-          --health-retries 5
+          --health-timeout 10s   # Increased timeout
+          --health-retries 10     # Increased retries
         ports:
           - 5432:5432
 
@@ -33,12 +33,13 @@ jobs:
 
       - name: Wait for PostgreSQL to be ready
         run: |
-          echo "Waiting for PostgreSQL to be ready..."
-          while ! docker exec postgres pg_isready -U surfaceinterval -d surface-interval-db; do
+          while ! pg_isready -h postgres -p 5432; do
             echo "Waiting for PostgreSQL to be ready..."
-            sleep 2
+            sleep 10   # Increased sleep interval
           done
-          echo "PostgreSQL is ready!"
+
+      - name: Check PostgreSQL logs
+        run: docker logs $(docker ps -q --filter ancestor=postgres:16)
 
       - name: Install dependencies
         run: |
